name: flying_animation
description: "Animation package for fly effect"
version: 0.0.2
homepage: "https://github.com/ganghee/fly_animation"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
